{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth2-proxy-injector.serviceAccountName" . }}
  labels:
    {{- include "oauth2-proxy-injector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oauth2-proxy-injector.fullname" . }}
  labels:
    {{- include "oauth2-proxy-injector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oauth2-proxy-injector.fullname" . }}
  labels:
    {{- include "oauth2-proxy-injector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "oauth2-proxy-injector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "oauth2-proxy-injector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
